language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
      before_install:
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install -e .
    - name: "Python 3.7.4 on maxOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install -e .
    - name: "3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
        - python -m pip install -r requirements.txt
        - python -m install -e .
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
scripts:
  - pytest --cov puzzlesolver
  - bash <(curl -s https://codecov.io/bash) 
notifications:
  email: false

# language: python
# python:
#   - "3.6"
# install:
#   - pip install -r requirements.txt
#   - pip install -e .
# script:
#   - pytest --cov puzzlesolver
#   - bash <(curl -s https://codecov.io/bash) 
# notifications:
#   email: false