language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov puzzlesolver
  - bash <(curl -s https://codecov.io/bash) 
notifications:
  email: false