language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
    - name: "Python 3.7.4 on maxOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/{ython36/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -e .
scripts:
  - pytest --cov puzzlesolver
  - bash <(curl -s https://codecov.io/bash) 
notifications:
  email: false

# language: python
# python:
#   - "3.6"
# install:
#   - pip install -r requirements.txt
#   - pip install -e .
# script:
#   - pytest --cov puzzlesolver
#   - bash <(curl -s https://codecov.io/bash) 
# notifications:
#   email: false