name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ants/UWAPI'
    steps:
      - name: Puzzles Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/github/GamesmanPuzzles
            echo "Pulling from GitHub ---------------------------------------------------"
            git pull
	    git checkout ants/UWAPI
            echo "Checking and installing new dependencies ------------------------------"
            pip3 install -r requirements.txt
            pip3 install -e .
            echo "Starting the server ---------------------------------------------------"
            sudo systemctl restart gamesman-puzzles-dev.service
            systemctl status gamesman-puzzles.service
          host: nyc.cs.berkeley.edu
          user: github
          key: ${{ secrets.KEY }}
  prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Puzzles Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/github/prod/GamesmanPuzzles
            echo "Pulling from GitHub ---------------------------------------------------"
            git pull
	    git checkout master
            echo "Checking and installing new dependencies ------------------------------"
            pip3 install -r requirements.txt
            pip3 install -e .
            echo "Starting the server ---------------------------------------------------"
            sudo systemctl restart gamesman-puzzles.service
            systemctl status gamesman-puzzles.service
          host: nyc.cs.berkeley.edu
          user: github
          key: ${{ secrets.KEY }}
